# Generated by Django 5.1.1 on 2024-10-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
